server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://125.185.128.147:3306/CodingWiki?characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ascoreams0321
    password: yim137654!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000







